### ISSUE TITLE
Calcular posicion de las puntas de la nave

### ISSUE THREAD

**Issue by Bade99** [Bade99/2019_1C_3051_Padawans#1]
Buenas gente abro los issues para que podamos ir poniendo las cosas que vamos haciendo o dejamos abiertas para que otro haga.
Asi tenemos centralizados los problemas jajaja

Dejo este xq llevo un par de horas tratando de encontrar una forma de calcular la posicion de la punta de la nave para que de ahí salga el misil pero las rotaciones son mas fuertes que yo. Si alguno quiere intentar es bienvenido.

**Comment by dipatata** [comment]
Ahi pushee, ahora sale desde las alas izquierda y derecha de manera random.  Hice una funcion calcularPosicionInicialMisil() que calcula desde donde salen los misiles. Lo que hice fue, al centro de la nave, le sume un vector distancia. Ese vector distancia es una distancia fija multiplicada por la coordenada esferica de la nave. Para lograr que salga desde el ala, le modifique un poco (0.1f) la coordenada acimultal. Esto seria como que la distancia la calcula no en la exacta direccion de la nave, sino un poco corrido. El efecto es que el vector distancia no vaya en direccion a la que apunta la nave, sino un poco corrido para el costado (o sea, para el lado del ala)

**Comment by Bade99** [comment]
Simply amazing
