### ISSUE TITLE
La camara se lockea cuando vas en direccion opuesta

### ISSUE THREAD

**Issue by Bade99** [Bade99/2019_1C_3051_Padawans#2]
Buenas andaba probando la cámara y vi que si das la vuelta y vas en dirección contraria la cámara se vuelve a bloquear como antes, no sé si ya sabías pero te aviso je.

**Comment by dipatata** [comment]
En realidad, esto se rompio por comentar esta linea

            ElapsedTime = 0.01f; //Lo hardcodeo hasta que sepamos bien como hacer esto

La posta es que todos se deberian mover a la misma velocidad. Al descomentar esto, la camara y la nave tienen distintos ciclos.
