### ISSUE TITLE
Corregir Camara look at

### ISSUE THREAD

**Issue by Bade99** [Bade99/2019_1C_3051_Padawans#3]
La camara debería mirar hacia adelante, no directo a la nave. Te dejo un ejemplo para cuando vuelvas de Iguazú je.
![camara](https://user-images.githubusercontent.com/31745377/58374857-09b24280-7f1c-11e9-916b-6b4ddc3b8cab.PNG)

**Comment by dipatata** [comment]
Le agregue una constante fija que se le suma al angulo polar DESVIO_ANGULO_POLAR en la nave para lograr ese efecto.
