### ISSUE TITLE
Implementar Bullet draw debugger

### ISSUE THREAD

**Issue by dipatata** [Bade99/2019_1C_3051_Padawans#6]
Implemente una clase que se llama DebugDrawerTest que usa bullet para dibujar los bounding box de sus colisiones.
Lo unico que me falta es implementar este metodo 
        public override void DrawLine(ref Vector3 from, ref Vector3 to, ref Vector3 color)
        {
            //Fran, podes hacer que este metodo dibuje una linea de from a to?
        }
Este metodo deberia dibujar una linea entre los vector from y to. Bullet hace el resto
Intente implementar exactamente como en tgcviewer. Use TgcArrow, use todo lo mismo que usa el render de los bounding box y no funca. 
Podes mirarlo a ver si es algo que no puedo darme cuenta?

**Comment by Bade99** [comment]
Esto ya lo implementé hace rato en Debug_Draw_Bullet, lo que si tenés que verlo metiendo un breakpoint y mirando frame a frame xq tarda muchísimo. Lo había asociado a una tecla, pero no se si ese código sigue por ahí

**Comment by dipatata** [comment]
Fran, puse exactamente las mismas lineas de tu viejo debugger y no funciona. Puede ser por los postprocesados? Intente desactivarlos pero al ponerlos en false pincha todo. Podes fijarte si podes desactivarlos bien o ayudarme a descubrir por que no renderiza los colliders?

**Comment by Bade99** [comment]
Ahora lo miro y te digo que onda
@dipatata

**Comment by dipatata** [comment]
@Bade99 fijate que con solo descomentar la linea que dibuja el debuggeado en PhyisicEngine dentro del update() ya deberia empezar a dibujar los colliders. De hecho comprobe que llama muchisimas veces a la clase que dibuja y le pasa coordenadas que en un principio tienen sentido

**Comment by Bade99** [comment]
@dipatata hmm creo que tu problema es que lo estás llamando en el update, banca que ahí termino

**Comment by Bade99** [comment]
@dipatata ya anda, lo puse que se activa un frame cuando apretás la "u", la probé solo frame a frame, fijate si te anda de la forma normal sacale lo de la "u"
