### ISSUE TITLE
[PRINCIPAL]Modo Dios

### ISSUE THREAD

**Issue by dipatata** [Bade99/2019_1C_3051_Padawans#8]
Agregue un modo Dios que se activa con IDDQD. (en honor al Doom)
Es un booleano en VariablesGlobales. Cuando pasa de false a true supongo que habria que mostrarlo de alguna manera en el HUD, un mensajito diciendo que estas en modo Dios?

**Comment by Bade99** [comment]
Apa jajaja, yo diría que lo pongamos con los drawText total es una funcionalidad que el usuario final no debería tener. Que te parece?
